version: '3'
services:
  http-transponder:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./config.yaml:/app/config.yaml
    restart: always
    environment:
      - TZ=Asia/Shanghai
